#!/usr/bin/env python3
"""
CIE-10-ES (ICD-10 Spanish) Generator - Part 1: Chapter definitions and detailed codes.
Generates a comprehensive JSON file with real ICD-10 codes and accurate Spanish descriptions.
"""

# Chapter ranges and Roman numerals
CHAPTERS = [
    ("I",    "A00", "B99", "Ciertas enfermedades infecciosas y parasitarias"),
    ("II",   "C00", "D49", "Neoplasias"),
    ("III",  "D50", "D89", "Enfermedades de la sangre y de los órganos hematopoyéticos"),
    ("IV",   "E00", "E90", "Enfermedades endocrinas, nutricionales y metabólicas"),
    ("V",    "F00", "F99", "Trastornos mentales y del comportamiento"),
    ("VI",   "G00", "G99", "Enfermedades del sistema nervioso"),
    ("VII",  "H00", "H59", "Enfermedades del ojo y sus anexos"),
    ("VIII", "H60", "H95", "Enfermedades del oído y de la apófisis mastoides"),
    ("IX",   "I00", "I99", "Enfermedades del sistema circulatorio"),
    ("X",    "J00", "J99", "Enfermedades del sistema respiratorio"),
    ("XI",   "K00", "K93", "Enfermedades del aparato digestivo"),
    ("XII",  "L00", "L99", "Enfermedades de la piel y del tejido subcutáneo"),
    ("XIII", "M00", "M99", "Enfermedades del sistema osteomuscular y del tejido conectivo"),
    ("XIV",  "N00", "N99", "Enfermedades del aparato genitourinario"),
    ("XV",   "O00", "O99", "Embarazo, parto y puerperio"),
    ("XVI",  "P00", "P96", "Ciertas afecciones originadas en el período perinatal"),
    ("XVII", "Q00", "Q99", "Malformaciones congénitas, deformidades y anomalías cromosómicas"),
    ("XVIII","R00", "R99", "Síntomas, signos y hallazgos anormales clínicos y de laboratorio"),
    ("XIX",  "S00", "T98", "Traumatismos, envenenamientos y algunas otras consecuencias de causas externas"),
    ("XX",   "V01", "Y98", "Causas externas de morbilidad y de mortalidad"),
    ("XXI",  "Z00", "Z99", "Factores que influyen en el estado de salud y contacto con los servicios de salud"),
    ("XXII", "U00", "U99", "Códigos para propósitos especiales"),
]

# ============================================================
# DETAILED CODES: Real ICD-10 codes with accurate Spanish descriptions
# Each entry: (code, description)
# These are organized by chapter for clarity
# ============================================================

DETAILED_CODES = {}

# ============================================================
# CHAPTER I: Infectious and parasitic diseases (A00-B99)
# ============================================================
DETAILED_CODES["I"] = [
    # A00 - Cólera
    ("A00", "Cólera"),
    ("A00.0", "Cólera debida a Vibrio cholerae O1, biotipo cholerae"),
    ("A00.1", "Cólera debida a Vibrio cholerae O1, biotipo El Tor"),
    ("A00.9", "Cólera, no especificado"),
    # A01 - Fiebres tifoidea y paratifoidea
    ("A01", "Fiebres tifoidea y paratifoidea"),
    ("A01.0", "Fiebre tifoidea"),
    ("A01.1", "Fiebre paratifoidea A"),
    ("A01.2", "Fiebre paratifoidea B"),
    ("A01.3", "Fiebre paratifoidea C"),
    ("A01.4", "Fiebre paratifoidea, no especificada"),
    # A02 - Otras infecciones por Salmonella
    ("A02", "Otras infecciones por Salmonella"),
    ("A02.0", "Enteritis por Salmonella"),
    ("A02.1", "Septicemia por Salmonella"),
    ("A02.2", "Infecciones localizadas por Salmonella"),
    ("A02.8", "Otras infecciones especificadas por Salmonella"),
    ("A02.9", "Infección por Salmonella, no especificada"),
    # A03 - Shigelosis
    ("A03", "Shigelosis"),
    ("A03.0", "Shigelosis debida a Shigella dysenteriae"),
    ("A03.1", "Shigelosis debida a Shigella flexneri"),
    ("A03.2", "Shigelosis debida a Shigella boydii"),
    ("A03.3", "Shigelosis debida a Shigella sonnei"),
    ("A03.8", "Otras shigelosis"),
    ("A03.9", "Shigelosis, no especificada"),
    # A04 - Otras infecciones intestinales bacterianas
    ("A04", "Otras infecciones intestinales bacterianas"),
    ("A04.0", "Infección intestinal debida a Escherichia coli enteropatógena"),
    ("A04.1", "Infección intestinal debida a Escherichia coli enterotoxígena"),
    ("A04.2", "Infección intestinal debida a Escherichia coli enteroinvasiva"),
    ("A04.3", "Infección intestinal debida a Escherichia coli enterohemorrágica"),
    ("A04.4", "Otras infecciones intestinales debidas a Escherichia coli"),
    ("A04.5", "Enteritis debida a Campylobacter"),
    ("A04.6", "Enteritis debida a Yersinia enterocolitica"),
    ("A04.7", "Enterocolitis debida a Clostridium difficile"),
    ("A04.8", "Otras infecciones intestinales bacterianas especificadas"),
    ("A04.9", "Infección intestinal bacteriana, no especificada"),
    # A05 - Otras intoxicaciones alimentarias bacterianas
    ("A05", "Otras intoxicaciones alimentarias bacterianas, no clasificadas en otra parte"),
    ("A05.0", "Intoxicación alimentaria estafilocócica"),
    ("A05.1", "Botulismo"),
    ("A05.2", "Intoxicación alimentaria debida a Clostridium perfringens"),
    ("A05.3", "Intoxicación alimentaria debida a Vibrio parahaemolyticus"),
    ("A05.4", "Intoxicación alimentaria debida a Bacillus cereus"),
    ("A05.8", "Otras intoxicaciones alimentarias bacterianas especificadas"),
    ("A05.9", "Intoxicación alimentaria bacteriana, no especificada"),
    # A06 - Amebiasis
    ("A06", "Amebiasis"),
    ("A06.0", "Disentería amebiana aguda"),
    ("A06.1", "Amebiasis intestinal crónica"),
    ("A06.2", "Colitis amebiana no disentérica"),
    ("A06.3", "Ameboma intestinal"),
    ("A06.4", "Absceso amebiano del hígado"),
    ("A06.5", "Absceso amebiano del pulmón"),
    ("A06.6", "Absceso amebiano del cerebro"),
    ("A06.7", "Amebiasis cutánea"),
    ("A06.8", "Infección amebiana de otras localizaciones"),
    ("A06.9", "Amebiasis, no especificada"),
    # A07 - Otras enfermedades intestinales debidas a protozoarios
    ("A07", "Otras enfermedades intestinales debidas a protozoarios"),
    ("A07.0", "Balantidiasis"),
    ("A07.1", "Giardiasis [lambliasis]"),
    ("A07.2", "Criptosporidiosis"),
    ("A07.3", "Isosporiasis"),
    ("A07.8", "Otras enfermedades intestinales especificadas debidas a protozoarios"),
    ("A07.9", "Enfermedad intestinal debida a protozoarios, no especificada"),
    # A08 - Infecciones intestinales debidas a virus
    ("A08", "Infecciones intestinales debidas a virus y otros organismos especificados"),
    ("A08.0", "Enteritis debida a rotavirus"),
    ("A08.1", "Gastroenteropatía aguda debida al agente de Norwalk"),
    ("A08.2", "Enteritis debida a adenovirus"),
    ("A08.3", "Otras enteritis virales"),
    ("A08.4", "Infección intestinal viral, no especificada"),
    ("A08.5", "Otras infecciones intestinales especificadas"),
    # A09 - Diarrea y gastroenteritis
    ("A09", "Diarrea y gastroenteritis de presunto origen infeccioso"),
    ("A09.0", "Otras gastroenteritis y colitis de origen infeccioso"),
    ("A09.9", "Gastroenteritis y colitis de origen no especificado"),
    # A15-A19 Tuberculosis
    ("A15", "Tuberculosis respiratoria, confirmada bacteriológica e histológicamente"),
    ("A15.0", "Tuberculosis del pulmón, confirmada por hallazgo microscópico del bacilo"),
    ("A15.1", "Tuberculosis del pulmón, confirmada únicamente por cultivo"),
    ("A15.2", "Tuberculosis del pulmón, confirmada histológicamente"),
    ("A15.3", "Tuberculosis del pulmón, confirmada por medios no especificados"),
    ("A15.4", "Tuberculosis de ganglios linfáticos intratorácicos, confirmada"),
    ("A15.5", "Tuberculosis de laringe, tráquea y bronquios, confirmada"),
    ("A15.6", "Pleuritis tuberculosa, confirmada"),
    ("A15.7", "Tuberculosis respiratoria primaria, confirmada"),
    ("A15.8", "Otras tuberculosis respiratorias, confirmadas"),
    ("A15.9", "Tuberculosis respiratoria no especificada, confirmada"),
    ("A16", "Tuberculosis respiratoria, no confirmada bacteriológica o histológicamente"),
    ("A16.0", "Tuberculosis del pulmón, con examen bacteriológico e histológico negativos"),
    ("A16.1", "Tuberculosis del pulmón, sin examen bacteriológico e histológico"),
    ("A16.2", "Tuberculosis del pulmón, sin mención de confirmación"),
    ("A16.3", "Tuberculosis de ganglios linfáticos intratorácicos, sin mención de confirmación"),
    ("A16.4", "Tuberculosis de laringe, tráquea y bronquios, sin mención de confirmación"),
    ("A16.5", "Pleuritis tuberculosa, sin mención de confirmación"),
    ("A16.7", "Tuberculosis respiratoria primaria, sin mención de confirmación"),
    ("A16.8", "Otras tuberculosis respiratorias, sin mención de confirmación"),
    ("A16.9", "Tuberculosis respiratoria, no especificada, sin mención de confirmación"),
    ("A17", "Tuberculosis del sistema nervioso"),
    ("A17.0", "Meningitis tuberculosa"),
    ("A17.1", "Tuberculoma meníngeo"),
    ("A17.8", "Otras tuberculosis del sistema nervioso"),
    ("A17.9", "Tuberculosis del sistema nervioso, no especificada"),
    ("A18", "Tuberculosis de otros órganos"),
    ("A18.0", "Tuberculosis de huesos y articulaciones"),
    ("A18.1", "Tuberculosis del aparato genitourinario"),
    ("A18.2", "Linfadenopatía periférica tuberculosa"),
    ("A18.3", "Tuberculosis de los intestinos, del peritoneo y de los ganglios mesentéricos"),
    ("A18.4", "Tuberculosis de la piel y del tejido subcutáneo"),
    ("A18.5", "Tuberculosis del ojo"),
    ("A18.6", "Tuberculosis del oído"),
    ("A18.7", "Tuberculosis de las glándulas suprarrenales"),
    ("A18.8", "Tuberculosis de otros órganos especificados"),
    ("A19", "Tuberculosis miliar"),
    ("A19.0", "Tuberculosis miliar aguda de un solo sitio especificado"),
    ("A19.1", "Tuberculosis miliar aguda de sitios múltiples"),
    ("A19.2", "Tuberculosis miliar aguda, no especificada"),
    ("A19.8", "Otras tuberculosis miliares"),
    ("A19.9", "Tuberculosis miliar, no especificada"),
    # A20-A28 Certain zoonotic bacterial diseases
    ("A20", "Peste"),
    ("A20.0", "Peste bubónica"),
    ("A20.1", "Peste celulocutánea"),
    ("A20.2", "Peste neumónica"),
    ("A20.3", "Meningitis por peste"),
    ("A20.7", "Peste septicémica"),
    ("A20.8", "Otras formas de peste"),
    ("A20.9", "Peste, no especificada"),
    ("A21", "Tularemia"),
    ("A21.0", "Tularemia ulceroglandular"),
    ("A21.1", "Tularemia oculoglandular"),
    ("A21.2", "Tularemia pulmonar"),
    ("A21.3", "Tularemia gastrointestinal"),
    ("A21.7", "Tularemia generalizada"),
    ("A21.8", "Otras formas de tularemia"),
    ("A21.9", "Tularemia, no especificada"),
    ("A22", "Carbunco [ántrax]"),
    ("A22.0", "Carbunco cutáneo"),
    ("A22.1", "Carbunco pulmonar"),
    ("A22.2", "Carbunco gastrointestinal"),
    ("A22.7", "Septicemia carbuncosa"),
    ("A22.8", "Otras formas de carbunco"),
    ("A22.9", "Carbunco, no especificado"),
    ("A23", "Brucelosis"),
    ("A23.0", "Brucelosis debida a Brucella melitensis"),
    ("A23.1", "Brucelosis debida a Brucella abortus"),
    ("A23.2", "Brucelosis debida a Brucella suis"),
    ("A23.3", "Brucelosis debida a Brucella canis"),
    ("A23.8", "Otras brucelosis"),
    ("A23.9", "Brucelosis, no especificada"),
    ("A24", "Muermo y melioidosis"),
    ("A24.0", "Muermo"),
    ("A24.1", "Melioidosis aguda y fulminante"),
    ("A24.2", "Melioidosis subaguda y crónica"),
    ("A24.3", "Otras melioidosis"),
    ("A24.4", "Melioidosis, no especificada"),
    ("A25", "Fiebres por mordedura de rata"),
    ("A25.0", "Espirilosis"),
    ("A25.1", "Estreptobacilos"),
    ("A25.9", "Fiebre por mordedura de rata, no especificada"),
    ("A26", "Erisipeloide"),
    ("A26.0", "Erisipeloide cutáneo"),
    ("A26.7", "Septicemia por Erysipelothrix"),
    ("A26.8", "Otras formas de erisipeloide"),
    ("A26.9", "Erisipeloide, no especificado"),
    ("A27", "Leptospirosis"),
    ("A27.0", "Leptospirosis icterohemorrrágica"),
    ("A27.8", "Otras formas de leptospirosis"),
    ("A27.9", "Leptospirosis, no especificada"),
    ("A28", "Otras enfermedades zoonóticas bacterianas, no clasificadas en otra parte"),
    ("A28.0", "Pasteurelosis"),
    ("A28.1", "Enfermedad por arañazo de gato"),
    ("A28.2", "Yersiniosis extraintestinal"),
    ("A28.8", "Otras enfermedades zoonóticas bacterianas especificadas"),
    ("A28.9", "Enfermedad zoonótica bacteriana, no especificada"),
    # A30-A49 Other bacterial diseases
    ("A30", "Lepra [enfermedad de Hansen]"),
    ("A30.0", "Lepra indeterminada"),
    ("A30.1", "Lepra tuberculoide"),
    ("A30.2", "Lepra tuberculoide limítrofe"),
    ("A30.3", "Lepra limítrofe"),
    ("A30.4", "Lepra lepromatosa limítrofe"),
    ("A30.5", "Lepra lepromatosa"),
    ("A30.8", "Otras formas de lepra"),
    ("A30.9", "Lepra, no especificada"),
    ("A31", "Infecciones debidas a otras micobacterias"),
    ("A31.0", "Infección pulmonar micobacteriana"),
    ("A31.1", "Infección cutánea micobacteriana"),
    ("A31.8", "Otras infecciones micobacterianas"),
    ("A31.9", "Infección micobacteriana, no especificada"),
    ("A32", "Listeriosis"),
    ("A32.0", "Listeriosis cutánea"),
    ("A32.1", "Meningitis y meningoencefalitis listeriana"),
    ("A32.7", "Septicemia listeriana"),
    ("A32.8", "Otras formas de listeriosis"),
    ("A32.9", "Listeriosis, no especificada"),
    ("A33", "Tétanos neonatal"),
    ("A34", "Tétanos obstétrico"),
    ("A35", "Otros tétanos"),
    ("A36", "Difteria"),
    ("A36.0", "Difteria faríngea"),
    ("A36.1", "Difteria nasofaríngea"),
    ("A36.2", "Difteria laríngea"),
    ("A36.3", "Difteria cutánea"),
    ("A36.8", "Otras difterias"),
    ("A36.9", "Difteria, no especificada"),
    ("A37", "Tos ferina [tos convulsa]"),
    ("A37.0", "Tos ferina debida a Bordetella pertussis"),
    ("A37.1", "Tos ferina debida a Bordetella parapertussis"),
    ("A37.8", "Tos ferina debida a otras especies de Bordetella"),
    ("A37.9", "Tos ferina, no especificada"),
    ("A38", "Escarlatina"),
    ("A39", "Infección meningocócica"),
    ("A39.0", "Meningitis meningocócica"),
    ("A39.1", "Síndrome de Waterhouse-Friderichsen"),
    ("A39.2", "Meningococemia aguda"),
    ("A39.3", "Meningococemia crónica"),
    ("A39.4", "Meningococemia, no especificada"),
    ("A39.5", "Carditis meningocócica"),
    ("A39.8", "Otras infecciones meningocócicas"),
    ("A39.9", "Infección meningocócica, no especificada"),
    ("A40", "Septicemia estreptocócica"),
    ("A40.0", "Septicemia debida a estreptococo del grupo A"),
    ("A40.1", "Septicemia debida a estreptococo del grupo B"),
    ("A40.2", "Septicemia debida a estreptococo del grupo D"),
    ("A40.3", "Septicemia debida a Streptococcus pneumoniae"),
    ("A40.8", "Otras septicemias estreptocócicas"),
    ("A40.9", "Septicemia estreptocócica, no especificada"),
    ("A41", "Otras septicemias"),
    ("A41.0", "Septicemia debida a Staphylococcus aureus"),
    ("A41.1", "Septicemia debida a otro estafilococo especificado"),
    ("A41.2", "Septicemia debida a estafilococo no especificado"),
    ("A41.3", "Septicemia debida a Haemophilus influenzae"),
    ("A41.4", "Septicemia debida a anaerobios"),
    ("A41.5", "Septicemia debida a otros organismos gramnegativos"),
    ("A41.8", "Otras septicemias especificadas"),
    ("A41.9", "Septicemia, no especificada"),
    ("A42", "Actinomicosis"),
    ("A42.0", "Actinomicosis pulmonar"),
    ("A42.1", "Actinomicosis abdominal"),
    ("A42.2", "Actinomicosis cervicofacial"),
    ("A42.7", "Septicemia actinomicótica"),
    ("A42.8", "Otras formas de actinomicosis"),
    ("A42.9", "Actinomicosis, no especificada"),
    ("A43", "Nocardiosis"),
    ("A43.0", "Nocardiosis pulmonar"),
    ("A43.1", "Nocardiosis cutánea"),
    ("A43.8", "Otras formas de nocardiosis"),
    ("A43.9", "Nocardiosis, no especificada"),
    ("A44", "Bartonelosis"),
    ("A44.0", "Bartonelosis sistémica"),
    ("A44.1", "Bartonelosis cutánea y mucocutánea"),
    ("A44.8", "Otras formas de bartonelosis"),
    ("A44.9", "Bartonelosis, no especificada"),
    ("A46", "Erisipela"),
    ("A48", "Otras enfermedades bacterianas, no clasificadas en otra parte"),
    ("A48.0", "Gangrena gaseosa"),
    ("A48.1", "Enfermedad de los legionarios"),
    ("A48.2", "Enfermedad de los legionarios no neumónica [fiebre de Pontiac]"),
    ("A48.3", "Síndrome del choque tóxico"),
    ("A48.4", "Fiebre purpúrica brasileña"),
    ("A48.8", "Otras enfermedades bacterianas especificadas"),
    ("A49", "Infección bacteriana de sitio no especificado"),
    ("A49.0", "Infección estafilocócica, sin otra especificación"),
    ("A49.1", "Infección estreptocócica, sin otra especificación"),
    ("A49.2", "Infección por Haemophilus influenzae, sin otra especificación"),
    ("A49.3", "Infección por Mycoplasma, sin otra especificación"),
    ("A49.8", "Otras infecciones bacterianas de sitio no especificado"),
    ("A49.9", "Infección bacteriana, no especificada"),
    # A50-A64 Infections with a predominantly sexual mode of transmission
    ("A50", "Sífilis congénita"),
    ("A50.0", "Sífilis congénita precoz sintomática"),
    ("A50.1", "Sífilis congénita precoz latente"),
    ("A50.2", "Sífilis congénita precoz, sin otra especificación"),
    ("A50.3", "Oculopatía sifilítica congénita tardía"),
    ("A50.4", "Neurosífilis congénita tardía"),
    ("A50.5", "Otras formas de sífilis congénita tardía sintomática"),
    ("A50.6", "Sífilis congénita tardía latente"),
    ("A50.7", "Sífilis congénita tardía, sin otra especificación"),
    ("A50.9", "Sífilis congénita, no especificada"),
    ("A51", "Sífilis precoz"),
    ("A51.0", "Sífilis genital primaria"),
    ("A51.1", "Sífilis anal primaria"),
    ("A51.2", "Sífilis primaria de otros sitios"),
    ("A51.3", "Sífilis secundaria de piel y membranas mucosas"),
    ("A51.4", "Otras sífilis secundarias"),
    ("A51.5", "Sífilis precoz latente"),
    ("A51.9", "Sífilis precoz, sin otra especificación"),
    ("A52", "Sífilis tardía"),
    ("A52.0", "Sífilis cardiovascular"),
    ("A52.1", "Neurosífilis sintomática"),
    ("A52.2", "Neurosífilis asintomática"),
    ("A52.3", "Neurosífilis, no especificada"),
    ("A52.7", "Otras sífilis tardías sintomáticas"),
    ("A52.8", "Sífilis tardía latente"),
    ("A52.9", "Sífilis tardía, no especificada"),
    ("A53", "Otras sífilis y las no especificadas"),
    ("A53.0", "Sífilis latente, no especificada como precoz o tardía"),
    ("A53.9", "Sífilis, no especificada"),
    ("A54", "Infección gonocócica"),
    ("A54.0", "Infección gonocócica del tracto genitourinario inferior sin absceso periuretral o de glándula accesoria"),
    ("A54.1", "Infección gonocócica del tracto genitourinario inferior con absceso periuretral y de glándula accesoria"),
    ("A54.2", "Pelviperitonitis gonocócica y otras infecciones gonocócicas genitourinarias"),
    ("A54.3", "Infección gonocócica del ojo"),
    ("A54.4", "Infección gonocócica del sistema osteomuscular"),
    ("A54.5", "Faringitis gonocócica"),
    ("A54.6", "Infección gonocócica del ano y del recto"),
    ("A54.8", "Otras infecciones gonocócicas"),
    ("A54.9", "Infección gonocócica, no especificada"),
    ("A55", "Linfogranuloma (venéreo) por clamidias"),
    ("A56", "Otras enfermedades de transmisión sexual debidas a clamidias"),
    ("A56.0", "Infección por clamidias del tracto genitourinario inferior"),
    ("A56.1", "Infección por clamidias del pelviperitoneo y otros órganos genitourinarios"),
    ("A56.2", "Infección por clamidias del tracto genitourinario, no especificada"),
    ("A56.3", "Infección del ano y del recto por clamidias"),
    ("A56.4", "Infección de la faringe por clamidias"),
    ("A56.8", "Infección de transmisión sexual por clamidias de otros sitios"),
    ("A57", "Chancro blando"),
    ("A58", "Granuloma inguinal"),
    ("A59", "Tricomoniasis"),
    ("A59.0", "Tricomoniasis urogenital"),
    ("A59.8", "Tricomoniasis de otros sitios"),
    ("A59.9", "Tricomoniasis, no especificada"),
    ("A60", "Infección anogenital debida a virus del herpes [herpes simple]"),
    ("A60.0", "Infección de genitales y del tracto urogenital debida a virus del herpes"),
    ("A60.1", "Infección de la piel perianal y del recto por virus del herpes"),
    ("A60.9", "Infección anogenital por virus del herpes, sin otra especificación"),
    ("A63", "Otras enfermedades de transmisión predominantemente sexual, no clasificadas en otra parte"),
    ("A63.0", "Verrugas anogenitales [venéreas]"),
    ("A63.8", "Otras enfermedades de transmisión predominantemente sexual, especificadas"),
    ("A64", "Enfermedad de transmisión sexual no especificada"),
    # A65-A69 Other spirochaetal diseases
    ("A65", "Sífilis no venérea"),
    ("A66", "Frambesia"),
    ("A66.0", "Lesiones iniciales de frambesia"),
    ("A66.1", "Papilomas múltiples y frambesia plantar húmeda"),
    ("A66.2", "Otras lesiones cutáneas precoces de frambesia"),
    ("A66.3", "Hiperqueratosis debida a frambesia"),
    ("A66.4", "Gomas y úlceras debidas a frambesia"),
    ("A66.5", "Gangosa"),
    ("A66.6", "Lesiones osteoarticulares debidas a frambesia"),
    ("A66.7", "Otras manifestaciones de frambesia"),
    ("A66.8", "Frambesia latente"),
    ("A66.9", "Frambesia, no especificada"),
    ("A67", "Pinta [carate]"),
    ("A67.0", "Lesiones primarias de la pinta"),
    ("A67.1", "Lesiones intermedias de la pinta"),
    ("A67.2", "Lesiones tardías de la pinta"),
    ("A67.3", "Lesiones mixtas de la pinta"),
    ("A67.9", "Pinta, no especificada"),
    ("A68", "Fiebres recurrentes"),
    ("A68.0", "Fiebre recurrente transmitida por piojos"),
    ("A68.1", "Fiebre recurrente transmitida por garrapatas"),
    ("A68.9", "Fiebre recurrente, no especificada"),
    ("A69", "Otras infecciones causadas por espiroquetas"),
    ("A69.0", "Estomatitis ulcerativa necrotizante"),
    ("A69.1", "Otras infecciones de Vincent"),
    ("A69.2", "Enfermedad de Lyme"),
    ("A69.8", "Otras infecciones especificadas por espiroquetas"),
    ("A69.9", "Infección por espiroquetas, no especificada"),
    # A70-A74 Other diseases caused by chlamydiae
    ("A70", "Infección debida a Chlamydia psittaci"),
    ("A71", "Tracoma"),
    ("A71.0", "Estado inicial de tracoma"),
    ("A71.1", "Estado activo de tracoma"),
    ("A71.9", "Tracoma, no especificado"),
    ("A74", "Otras enfermedades causadas por clamidias"),
    ("A74.0", "Conjuntivitis por clamidias"),
    ("A74.8", "Otras enfermedades por clamidias"),
    ("A74.9", "Infección por clamidias, no especificada"),
    # A75-A79 Rickettsioses
    ("A75", "Tifus"),
    ("A75.0", "Tifus epidémico debido a Rickettsia prowazekii transmitido por piojos"),
    ("A75.1", "Tifus recrudescente [enfermedad de Brill]"),
    ("A75.2", "Tifus debida a Rickettsia typhi"),
    ("A75.3", "Tifus debida a Rickettsia tsutsugamushi"),
    ("A75.9", "Tifus, no especificado"),
    ("A77", "Fiebre maculosa [rickettsiosis transmitida por garrapatas]"),
    ("A77.0", "Fiebre maculosa debida a Rickettsia rickettsii"),
    ("A77.1", "Fiebre maculosa debida a Rickettsia conorii"),
    ("A77.2", "Fiebre maculosa debida a Rickettsia siberica"),
    ("A77.3", "Fiebre maculosa debida a Rickettsia australis"),
    ("A77.8", "Otras fiebres maculosas"),
    ("A77.9", "Fiebre maculosa, no especificada"),
    ("A78", "Fiebre Q"),
    ("A79", "Otras rickettsiosis"),
    ("A79.0", "Fiebre de las trincheras"),
    ("A79.1", "Rickettsiosis pustulosa debida a Rickettsia akari"),
    ("A79.8", "Otras rickettsiosis especificadas"),
    ("A79.9", "Rickettsiosis, no especificada"),
    # A80-A89 Viral infections of the central nervous system
    ("A80", "Poliomielitis aguda"),
    ("A80.0", "Poliomielitis aguda paralítica, asociada a vacuna"),
    ("A80.1", "Poliomielitis aguda paralítica debida a virus salvaje importado"),
    ("A80.2", "Poliomielitis aguda paralítica debida a virus salvaje autóctono"),
    ("A80.3", "Otras poliomielitis agudas paralíticas y las no especificadas"),
    ("A80.4", "Poliomielitis aguda no paralítica"),
    ("A80.9", "Poliomielitis aguda, sin otra especificación"),
    ("A81", "Infecciones del sistema nervioso central por virus atípico"),
    ("A81.0", "Enfermedad de Creutzfeldt-Jakob"),
    ("A81.1", "Panencefalitis esclerosante subaguda"),
    ("A81.2", "Leucoencefalopatía multifocal progresiva"),
    ("A81.8", "Otras infecciones del sistema nervioso central por virus atípico"),
    ("A81.9", "Infección del sistema nervioso central por virus atípico, sin otra especificación"),
    ("A82", "Rabia"),
    ("A82.0", "Rabia selvática"),
    ("A82.1", "Rabia urbana"),
    ("A82.9", "Rabia, sin otra especificación"),
    ("A83", "Encefalitis viral transmitida por mosquitos"),
    ("A83.0", "Encefalitis japonesa"),
    ("A83.1", "Encefalitis equina del oeste"),
    ("A83.2", "Encefalitis equina del este"),
    ("A83.3", "Encefalitis de San Luis"),
    ("A83.4", "Encefalitis australiana"),
    ("A83.5", "Encefalitis californiana"),
    ("A83.6", "Enfermedad por virus Rocío"),
    ("A83.8", "Otras encefalitis virales transmitidas por mosquitos"),
    ("A83.9", "Encefalitis viral transmitida por mosquitos, sin otra especificación"),
    ("A84", "Encefalitis viral transmitida por garrapatas"),
    ("A84.0", "Encefalitis del Lejano Oriente transmitida por garrapatas"),
    ("A84.1", "Encefalitis centroeuropea transmitida por garrapatas"),
    ("A84.8", "Otras encefalitis virales transmitidas por garrapatas"),
    ("A84.9", "Encefalitis viral transmitida por garrapatas, sin otra especificación"),
    ("A85", "Otras encefalitis virales, no clasificadas en otra parte"),
    ("A85.0", "Encefalitis enteroviral"),
    ("A85.1", "Encefalitis por adenovirus"),
    ("A85.2", "Encefalitis viral transmitida por artrópodos, sin otra especificación"),
    ("A85.8", "Otras encefalitis virales especificadas"),
    ("A86", "Encefalitis viral, no especificada"),
    ("A87", "Meningitis viral"),
    ("A87.0", "Meningitis enteroviral"),
    ("A87.1", "Meningitis por adenovirus"),
    ("A87.2", "Coriomeningitis linfocítica"),
    ("A87.8", "Otras meningitis virales"),
    ("A87.9", "Meningitis viral, no especificada"),
    ("A88", "Otras infecciones virales del sistema nervioso central, no clasificadas en otra parte"),
    ("A88.0", "Fiebre exantemática enteroviral [exantema de Boston]"),
    ("A88.1", "Vértigo epidémico"),
    ("A88.8", "Otras infecciones virales especificadas del sistema nervioso central"),
    ("A89", "Infección viral del sistema nervioso central, no especificada"),
    # A90-A99 Arthropod-borne viral fevers and viral haemorrhagic fevers
    ("A90", "Fiebre del dengue [dengue clásico]"),
    ("A91", "Fiebre del dengue hemorrágico"),
    ("A92", "Otras fiebres virales transmitidas por mosquitos"),
    ("A92.0", "Enfermedad por virus Chikungunya"),
    ("A92.1", "Fiebre de O'nyong-nyong"),
    ("A92.2", "Fiebre equina venezolana"),
    ("A92.3", "Fiebre del Nilo Occidental"),
    ("A92.4", "Fiebre del Valle del Rift"),
    ("A92.8", "Otras fiebres virales especificadas transmitidas por mosquitos"),
    ("A92.9", "Fiebre viral transmitida por mosquitos, sin otra especificación"),
    ("A93", "Otras fiebres virales transmitidas por artrópodos, no clasificadas en otra parte"),
    ("A93.0", "Enfermedad por virus Oropouche"),
    ("A93.1", "Fiebre por flebótomos"),
    ("A93.2", "Fiebre de Colorado transmitida por garrapatas"),
    ("A93.8", "Otras fiebres virales especificadas transmitidas por artrópodos"),
    ("A94", "Fiebre viral transmitida por artrópodos, no especificada"),
    ("A95", "Fiebre amarilla"),
    ("A95.0", "Fiebre amarilla selvática"),
    ("A95.1", "Fiebre amarilla urbana"),
    ("A95.9", "Fiebre amarilla, no especificada"),
    ("A96", "Fiebre hemorrágica por arenavirus"),
    ("A96.0", "Fiebre hemorrágica de Junín"),
    ("A96.1", "Fiebre hemorrágica de Machupo"),
    ("A96.2", "Fiebre de Lassa"),
    ("A96.8", "Otras fiebres hemorrágicas por arenavirus"),
    ("A96.9", "Fiebre hemorrágica por arenavirus, sin otra especificación"),
    ("A98", "Otras fiebres virales hemorrágicas, no clasificadas en otra parte"),
    ("A98.0", "Fiebre hemorrágica de Crimea-Congo"),
    ("A98.1", "Fiebre hemorrágica de Omsk"),
    ("A98.2", "Enfermedad de la selva de Kyasanur"),
    ("A98.3", "Enfermedad por virus de Marburg"),
    ("A98.4", "Enfermedad por virus del Ébola"),
    ("A98.5", "Fiebre hemorrágica con síndrome renal"),
    ("A98.8", "Otras fiebres virales hemorrágicas especificadas"),
    ("A99", "Fiebre viral hemorrágica, no especificada"),
    # B00-B09 Viral infections characterized by skin and mucous membrane lesions
    ("B00", "Infecciones herpéticas [herpes simple]"),
    ("B00.0", "Eccema herpético"),
    ("B00.1", "Dermatitis vesicular herpética"),
    ("B00.2", "Gingivoestomatitis y faringoamigdalitis herpética"),
    ("B00.3", "Meningitis herpética"),
    ("B00.4", "Encefalitis herpética"),
    ("B00.5", "Oculopatía herpética"),
    ("B00.7", "Enfermedad herpética diseminada"),
    ("B00.8", "Otras formas de infección herpética"),
    ("B00.9", "Infección debida a virus del herpes simple, sin otra especificación"),
    ("B01", "Varicela"),
    ("B01.0", "Meningitis debida a varicela"),
    ("B01.1", "Encefalitis debida a varicela"),
    ("B01.2", "Neumonía debida a varicela"),
    ("B01.8", "Varicela con otras complicaciones"),
    ("B01.9", "Varicela sin complicaciones"),
    ("B02", "Herpes zóster [zona]"),
    ("B02.0", "Encefalitis debida a herpes zóster"),
    ("B02.1", "Meningitis debida a herpes zóster"),
    ("B02.2", "Herpes zóster con otras complicaciones del sistema nervioso"),
    ("B02.3", "Herpes zóster ocular"),
    ("B02.7", "Herpes zóster diseminado"),
    ("B02.8", "Herpes zóster con otras complicaciones"),
    ("B02.9", "Herpes zóster sin complicaciones"),
    ("B03", "Viruela"),
    ("B04", "Viruela de los monos"),
    ("B05", "Sarampión"),
    ("B05.0", "Sarampión complicado con encefalitis"),
    ("B05.1", "Sarampión complicado con meningitis"),
    ("B05.2", "Sarampión complicado con neumonía"),
    ("B05.3", "Sarampión complicado con otitis media"),
    ("B05.4", "Sarampión con complicaciones intestinales"),
    ("B05.8", "Sarampión con otras complicaciones"),
    ("B05.9", "Sarampión sin complicaciones"),
    ("B06", "Rubéola [sarampión alemán]"),
    ("B06.0", "Rubéola con complicaciones neurológicas"),
    ("B06.8", "Rubéola con otras complicaciones"),
    ("B06.9", "Rubéola sin complicaciones"),
    ("B07", "Verrugas víricas"),
    ("B08", "Otras infecciones virales caracterizadas por lesiones de la piel y de las membranas mucosas, no clasificadas en otra parte"),
    ("B08.0", "Otras infecciones debidas a ortopoxvirus"),
    ("B08.1", "Molusco contagioso"),
    ("B08.2", "Exantema súbito [sexta enfermedad]"),
    ("B08.3", "Eritema infeccioso [quinta enfermedad]"),
    ("B08.4", "Estomatitis vesicular enteroviral con exantema"),
    ("B08.5", "Faringitis vesicular enteroviral"),
    ("B08.8", "Otras infecciones virales especificadas caracterizadas por lesiones de la piel y de las membranas mucosas"),
    ("B09", "Infección viral no especificada, caracterizada por lesiones de la piel y de las membranas mucosas"),
    # B15-B19 Viral hepatitis
    ("B15", "Hepatitis aguda tipo A"),
    ("B15.0", "Hepatitis aguda tipo A con coma hepático"),
    ("B15.9", "Hepatitis aguda tipo A sin coma hepático"),
    ("B16", "Hepatitis aguda tipo B"),
    ("B16.0", "Hepatitis aguda tipo B con agente delta (coinfección), con coma hepático"),
    ("B16.1", "Hepatitis aguda tipo B con agente delta (coinfección), sin coma hepático"),
    ("B16.2", "Hepatitis aguda tipo B sin agente delta, con coma hepático"),
    ("B16.9", "Hepatitis aguda tipo B sin agente delta y sin coma hepático"),
    ("B17", "Otras hepatitis virales agudas"),
    ("B17.0", "Sobreinfección delta aguda del portador de hepatitis B"),
    ("B17.1", "Hepatitis aguda tipo C"),
    ("B17.2", "Hepatitis aguda tipo E"),
    ("B17.8", "Otras hepatitis virales agudas especificadas"),
    ("B18", "Hepatitis viral crónica"),
    ("B18.0", "Hepatitis viral tipo B crónica con agente delta"),
    ("B18.1", "Hepatitis viral tipo B crónica sin agente delta"),
    ("B18.2", "Hepatitis viral tipo C crónica"),
    ("B18.8", "Otras hepatitis virales crónicas"),
    ("B18.9", "Hepatitis viral crónica, sin otra especificación"),
    ("B19", "Hepatitis viral, sin otra especificación"),
    ("B19.0", "Hepatitis viral no especificada con coma"),
    ("B19.9", "Hepatitis viral no especificada sin coma"),
    # B20-B24 HIV disease
    ("B20", "Enfermedad por virus de la inmunodeficiencia humana [VIH], resultante en enfermedades infecciosas y parasitarias"),
    ("B20.0", "Enfermedad por VIH, resultante en infección micobacteriana"),
    ("B20.1", "Enfermedad por VIH, resultante en otras infecciones bacterianas"),
    ("B20.2", "Enfermedad por VIH, resultante en enfermedad por citomegalovirus"),
    ("B20.3", "Enfermedad por VIH, resultante en otras infecciones virales"),
    ("B20.4", "Enfermedad por VIH, resultante en candidiasis"),
    ("B20.5", "Enfermedad por VIH, resultante en otras micosis"),
    ("B20.6", "Enfermedad por VIH, resultante en neumonía por Pneumocystis jirovecii"),
    ("B20.7", "Enfermedad por VIH, resultante en infecciones múltiples"),
    ("B20.8", "Enfermedad por VIH, resultante en otras enfermedades infecciosas y parasitarias"),
    ("B20.9", "Enfermedad por VIH, resultante en enfermedad infecciosa o parasitaria no especificada"),
    ("B21", "Enfermedad por VIH, resultante en neoplasias malignas"),
    ("B21.0", "Enfermedad por VIH, resultante en sarcoma de Kaposi"),
    ("B21.1", "Enfermedad por VIH, resultante en linfoma de Burkitt"),
    ("B21.2", "Enfermedad por VIH, resultante en otros tipos de linfoma no Hodgkin"),
    ("B21.3", "Enfermedad por VIH, resultante en otros tumores malignos del tejido linfoide, hematopoyético y tejidos relacionados"),
    ("B21.7", "Enfermedad por VIH, resultante en neoplasias malignas múltiples"),
    ("B21.8", "Enfermedad por VIH, resultante en otras neoplasias malignas"),
    ("B21.9", "Enfermedad por VIH, resultante en neoplasia maligna no especificada"),
    ("B22", "Enfermedad por VIH, resultante en otras enfermedades especificadas"),
    ("B22.0", "Enfermedad por VIH, resultante en encefalopatía"),
    ("B22.1", "Enfermedad por VIH, resultante en neumonitis linfoide intersticial"),
    ("B22.2", "Enfermedad por VIH, resultante en síndrome caquéctico"),
    ("B22.7", "Enfermedad por VIH, resultante en enfermedades múltiples clasificadas en otra parte"),
    ("B23", "Enfermedad por VIH, resultante en otras afecciones"),
    ("B23.0", "Síndrome de infección aguda debida a VIH"),
    ("B23.1", "Enfermedad por VIH, resultante en linfadenopatía generalizada (persistente)"),
    ("B23.2", "Enfermedad por VIH, resultante en anomalías hematológicas e inmunológicas, no clasificadas en otra parte"),
    ("B23.8", "Enfermedad por VIH, resultante en otras afecciones especificadas"),
    ("B24", "Enfermedad por virus de la inmunodeficiencia humana [VIH], sin otra especificación"),
    # B25-B34 Other viral diseases
    ("B25", "Enfermedad debida a virus citomegálico"),
    ("B25.0", "Neumonitis debida a virus citomegálico"),
    ("B25.1", "Hepatitis debida a virus citomegálico"),
    ("B25.2", "Pancreatitis debida a virus citomegálico"),
    ("B25.8", "Otras enfermedades debidas a virus citomegálico"),
    ("B25.9", "Enfermedad debida a virus citomegálico, no especificada"),
    ("B26", "Parotiditis infecciosa"),
    ("B26.0", "Orquitis por parotiditis"),
    ("B26.1", "Meningitis por parotiditis"),
    ("B26.2", "Encefalitis por parotiditis"),
    ("B26.3", "Pancreatitis por parotiditis"),
    ("B26.8", "Parotiditis infecciosa con otras complicaciones"),
    ("B26.9", "Parotiditis infecciosa, sin complicaciones"),
    ("B27", "Mononucleosis infecciosa"),
    ("B27.0", "Mononucleosis debida a herpes virus gamma"),
    ("B27.1", "Mononucleosis debida a citomegalovirus"),
    ("B27.8", "Otras mononucleosis infecciosas"),
    ("B27.9", "Mononucleosis infecciosa, no especificada"),
    ("B30", "Conjuntivitis viral"),
    ("B30.0", "Queratoconjuntivitis debida a adenovirus"),
    ("B30.1", "Conjuntivitis debida a adenovirus"),
    ("B30.2", "Faringoconjuntivitis viral"),
    ("B30.3", "Conjuntivitis hemorrágica aguda (enteroviral)"),
    ("B30.8", "Otras conjuntivitis virales"),
    ("B30.9", "Conjuntivitis viral, no especificada"),
    ("B33", "Otras enfermedades virales, no clasificadas en otra parte"),
    ("B33.0", "Mialgia epidémica"),
    ("B33.1", "Enfermedad de Ross River"),
    ("B33.2", "Carditis viral"),
    ("B33.3", "Infecciones debidas a retrovirus, no clasificadas en otra parte"),
    ("B33.4", "Síndrome pulmonar (cardio-) por hantavirus"),
    ("B33.8", "Otras enfermedades virales especificadas"),
    ("B34", "Infección viral de sitio no especificado"),
    ("B34.0", "Infección debida a adenovirus, sin otra especificación"),
    ("B34.1", "Infección debida a enterovirus, sin otra especificación"),
    ("B34.2", "Infección debida a coronavirus, sin otra especificación"),
    ("B34.3", "Infección debida a parvovirus, sin otra especificación"),
    ("B34.4", "Infección debida a papovavirus, sin otra especificación"),
    ("B34.8", "Otras infecciones virales de sitio no especificado"),
    ("B34.9", "Infección viral, no especificada"),
    # B35-B49 Mycoses
    ("B35", "Dermatofitosis"),
    ("B35.0", "Tiña de la barba y del cuero cabelludo"),
    ("B35.1", "Tiña de las uñas"),
    ("B35.2", "Tiña de la mano"),
    ("B35.3", "Tiña del pie [pie de atleta]"),
    ("B35.4", "Tiña del cuerpo"),
    ("B35.5", "Tiña imbricada [tokelau]"),
    ("B35.6", "Tiña inguinal [tiña crural]"),
    ("B35.8", "Otras dermatofitosis"),
    ("B35.9", "Dermatofitosis, no especificada"),
    ("B36", "Otras micosis superficiales"),
    ("B36.0", "Pitiriasis versicolor"),
    ("B36.1", "Tiña negra"),
    ("B36.2", "Piedra blanca"),
    ("B36.3", "Piedra negra"),
    ("B36.8", "Otras micosis superficiales especificadas"),
    ("B36.9", "Micosis superficial, sin otra especificación"),
    ("B37", "Candidiasis"),
    ("B37.0", "Estomatitis por Candida"),
    ("B37.1", "Candidiasis pulmonar"),
    ("B37.2", "Candidiasis de la piel y de las uñas"),
    ("B37.3", "Candidiasis de la vulva y de la vagina"),
    ("B37.4", "Candidiasis de otras localizaciones urogenitales"),
    ("B37.5", "Meningitis debida a Candida"),
    ("B37.6", "Endocarditis debida a Candida"),
    ("B37.7", "Septicemia debida a Candida"),
    ("B37.8", "Candidiasis de otros sitios"),
    ("B37.9", "Candidiasis, no especificada"),
    ("B38", "Coccidioidomicosis"),
    ("B38.0", "Coccidioidomicosis pulmonar aguda"),
    ("B38.1", "Coccidioidomicosis pulmonar crónica"),
    ("B38.2", "Coccidioidomicosis pulmonar, no especificada"),
    ("B38.3", "Coccidioidomicosis cutánea"),
    ("B38.4", "Meningitis por coccidioidomicosis"),
    ("B38.7", "Coccidioidomicosis diseminada"),
    ("B38.8", "Otras formas de coccidioidomicosis"),
    ("B38.9", "Coccidioidomicosis, no especificada"),
    ("B39", "Histoplasmosis"),
    ("B39.0", "Infección pulmonar aguda debida a Histoplasma capsulatum"),
    ("B39.1", "Infección pulmonar crónica debida a Histoplasma capsulatum"),
    ("B39.2", "Infección pulmonar debida a Histoplasma capsulatum, sin otra especificación"),
    ("B39.3", "Infección diseminada debida a Histoplasma capsulatum"),
    ("B39.4", "Histoplasmosis debida a Histoplasma capsulatum, sin otra especificación"),
    ("B39.5", "Infección debida a Histoplasma duboisii"),
    ("B39.9", "Histoplasmosis, no especificada"),
    ("B40", "Blastomicosis"),
    ("B40.0", "Blastomicosis pulmonar aguda"),
    ("B40.1", "Blastomicosis pulmonar crónica"),
    ("B40.2", "Blastomicosis pulmonar, no especificada"),
    ("B40.3", "Blastomicosis cutánea"),
    ("B40.7", "Blastomicosis diseminada"),
    ("B40.8", "Otras formas de blastomicosis"),
    ("B40.9", "Blastomicosis, no especificada"),
    ("B41", "Paracoccidioidomicosis"),
    ("B41.0", "Paracoccidioidomicosis pulmonar"),
    ("B41.7", "Paracoccidioidomicosis diseminada"),
    ("B41.8", "Otras formas de paracoccidioidomicosis"),
    ("B41.9", "Paracoccidioidomicosis, no especificada"),
    ("B42", "Esporotricosis"),
    ("B42.0", "Esporotricosis pulmonar"),
    ("B42.1", "Esporotricosis linfocutánea"),
    ("B42.7", "Esporotricosis diseminada"),
    ("B42.8", "Otras formas de esporotricosis"),
    ("B42.9", "Esporotricosis, no especificada"),
    ("B43", "Cromomicosis y absceso feomicótico"),
    ("B43.0", "Cromomicosis cutánea"),
    ("B43.1", "Absceso cerebral feomicótico"),
    ("B43.2", "Absceso y quiste feomicótico subcutáneo"),
    ("B43.8", "Otras formas de cromomicosis"),
    ("B43.9", "Cromomicosis, no especificada"),
    ("B44", "Aspergilosis"),
    ("B44.0", "Aspergilosis pulmonar invasiva"),
    ("B44.1", "Otras aspergilosis pulmonares"),
    ("B44.2", "Aspergilosis amigdalina"),
    ("B44.7", "Aspergilosis diseminada"),
    ("B44.8", "Otras formas de aspergilosis"),
    ("B44.9", "Aspergilosis, no especificada"),
    ("B45", "Criptococosis"),
    ("B45.0", "Criptococosis pulmonar"),
    ("B45.1", "Criptococosis cerebral"),
    ("B45.2", "Criptococosis cutánea"),
    ("B45.3", "Criptococosis ósea"),
    ("B45.7", "Criptococosis diseminada"),
    ("B45.8", "Otras formas de criptococosis"),
    ("B45.9", "Criptococosis, no especificada"),
    ("B46", "Cigomicosis"),
    ("B46.0", "Mucormicosis pulmonar"),
    ("B46.1", "Mucormicosis rinocerebral"),
    ("B46.2", "Mucormicosis gastrointestinal"),
    ("B46.3", "Mucormicosis cutánea"),
    ("B46.4", "Mucormicosis diseminada"),
    ("B46.5", "Mucormicosis, no especificada"),
    ("B46.8", "Otras cigomicosis"),
    ("B46.9", "Cigomicosis, no especificada"),
    ("B47", "Micetoma"),
    ("B47.0", "Eumicetoma"),
    ("B47.1", "Actinomicetoma"),
    ("B47.9", "Micetoma, no especificado"),
    ("B48", "Otras micosis, no clasificadas en otra parte"),
    ("B48.0", "Lobomicosis"),
    ("B48.1", "Rinosporidiosis"),
    ("B48.2", "Alesqueriasis"),
    ("B48.3", "Geotricosis"),
    ("B48.4", "Penicilosis"),
    ("B48.7", "Micosis oportunistas"),
    ("B48.8", "Otras micosis especificadas"),
    ("B49", "Micosis, no especificada"),
    # B50-B64 Protozoal diseases
    ("B50", "Paludismo [malaria] debido a Plasmodium falciparum"),
    ("B50.0", "Paludismo debido a Plasmodium falciparum con complicaciones cerebrales"),
    ("B50.8", "Otro paludismo grave y complicado debido a Plasmodium falciparum"),
    ("B50.9", "Paludismo debido a Plasmodium falciparum, sin otra especificación"),
    ("B51", "Paludismo [malaria] debido a Plasmodium vivax"),
    ("B51.0", "Paludismo debido a Plasmodium vivax con rotura esplénica"),
    ("B51.8", "Paludismo debido a Plasmodium vivax con otras complicaciones"),
    ("B51.9", "Paludismo debido a Plasmodium vivax sin complicaciones"),
    ("B52", "Paludismo [malaria] debido a Plasmodium malariae"),
    ("B52.0", "Paludismo debido a Plasmodium malariae con nefropatía"),
    ("B52.8", "Paludismo debido a Plasmodium malariae con otras complicaciones"),
    ("B52.9", "Paludismo debido a Plasmodium malariae sin complicaciones"),
    ("B53", "Otro paludismo confirmado parasitológicamente"),
    ("B53.0", "Paludismo debido a Plasmodium ovale"),
    ("B53.1", "Paludismo debido a plasmodios de los simios"),
    ("B53.8", "Otro paludismo, confirmado parasitológicamente, no clasificado en otra parte"),
    ("B54", "Paludismo [malaria] no especificado"),
    ("B55", "Leishmaniasis"),
    ("B55.0", "Leishmaniasis visceral"),
    ("B55.1", "Leishmaniasis cutánea"),
    ("B55.2", "Leishmaniasis mucocutánea"),
    ("B55.9", "Leishmaniasis, no especificada"),
    ("B56", "Tripanosomiasis africana"),
    ("B56.0", "Tripanosomiasis gambiana"),
    ("B56.1", "Tripanosomiasis rhodesiana"),
    ("B56.9", "Tripanosomiasis africana, no especificada"),
    ("B57", "Enfermedad de Chagas"),
    ("B57.0", "Enfermedad de Chagas aguda que afecta al corazón"),
    ("B57.1", "Enfermedad de Chagas aguda que no afecta al corazón"),
    ("B57.2", "Enfermedad de Chagas (crónica) que afecta al corazón"),
    ("B57.3", "Enfermedad de Chagas (crónica) que afecta al sistema digestivo"),
    ("B57.4", "Enfermedad de Chagas (crónica) que afecta al sistema nervioso"),
    ("B57.5", "Enfermedad de Chagas (crónica) que afecta a otros órganos"),
    ("B58", "Toxoplasmosis"),
    ("B58.0", "Oculopatía debida a toxoplasma"),
    ("B58.1", "Hepatitis debida a toxoplasma"),
    ("B58.2", "Meningoencefalitis debida a toxoplasma"),
    ("B58.3", "Toxoplasmosis pulmonar"),
    ("B58.8", "Toxoplasmosis con otro órgano afectado"),
    ("B58.9", "Toxoplasmosis, no especificada"),
    ("B59", "Neumocistosis"),
    ("B60", "Otras enfermedades debidas a protozoarios, no clasificadas en otra parte"),
    ("B60.0", "Babesiosis"),
    ("B60.1", "Acantamebiasis"),
    ("B60.2", "Naegleriasis"),
    ("B60.8", "Otras enfermedades especificadas debidas a protozoarios"),
    ("B64", "Enfermedad debida a protozoarios, no especificada"),
    # B65-B83 Helminthiases
    ("B65", "Esquistosomiasis [bilharziasis]"),
    ("B65.0", "Esquistosomiasis debida a Schistosoma haematobium [esquistosomiasis urinaria]"),
    ("B65.1", "Esquistosomiasis debida a Schistosoma mansoni [esquistosomiasis intestinal]"),
    ("B65.2", "Esquistosomiasis debida a Schistosoma japonicum"),
    ("B65.8", "Otras esquistosomiasis"),
    ("B65.9", "Esquistosomiasis, no especificada"),
    ("B66", "Otras infecciones debidas a trematodos"),
    ("B66.0", "Opistorquiasis"),
    ("B66.1", "Clonorquiasis"),
    ("B66.2", "Dicroceliasis"),
    ("B66.3", "Fascioliasis"),
    ("B66.4", "Paragonimiasis"),
    ("B66.5", "Fasciolopsiasis"),
    ("B66.8", "Otras infecciones especificadas debidas a trematodos"),
    ("B66.9", "Infección debida a trematodos, no especificada"),
    ("B67", "Equinococosis"),
    ("B67.0", "Infección del hígado debida a Echinococcus granulosus"),
    ("B67.1", "Infección del pulmón debida a Echinococcus granulosus"),
    ("B67.2", "Infección de hueso debida a Echinococcus granulosus"),
    ("B67.3", "Infección de otro órgano y de sitios múltiples por Echinococcus granulosus"),
    ("B67.4", "Infección debida a Echinococcus granulosus, sin otra especificación"),
    ("B67.5", "Infección del hígado debida a Echinococcus multilocularis"),
    ("B67.6", "Infección de otro órgano y de sitios múltiples por Echinococcus multilocularis"),
    ("B67.7", "Infección debida a Echinococcus multilocularis, sin otra especificación"),
    ("B67.8", "Equinococosis del hígado, no especificada"),
    ("B67.9", "Equinococosis, otra y la no especificada"),
    ("B68", "Teniasis"),
    ("B68.0", "Teniasis debida a Taenia solium"),
    ("B68.1", "Teniasis debida a Taenia saginata"),
    ("B68.9", "Teniasis, no especificada"),
    ("B69", "Cisticercosis"),
    ("B69.0", "Cisticercosis del sistema nervioso central"),
    ("B69.1", "Cisticercosis del ojo"),
    ("B69.8", "Cisticercosis de otros sitios"),
    ("B69.9", "Cisticercosis, no especificada"),
    ("B70", "Difilobotriasis y esparganosis"),
    ("B70.0", "Difilobotriasis"),
    ("B70.1", "Esparganosis"),
    ("B71", "Otras infecciones debidas a cestodos"),
    ("B71.0", "Himenolepiasis"),
    ("B71.1", "Dipilidiasis"),
    ("B71.8", "Otras infecciones especificadas debidas a cestodos"),
    ("B71.9", "Infección debida a cestodos, no especificada"),
    ("B72", "Dracontiasis"),
    ("B73", "Oncocercosis"),
    ("B74", "Filariasis"),
    ("B74.0", "Filariasis debida a Wuchereria bancrofti"),
    ("B74.1", "Filariasis debida a Brugia malayi"),
    ("B74.2", "Filariasis debida a Brugia timori"),
    ("B74.3", "Loaiasis"),
    ("B74.4", "Mansoneliasis"),
    ("B74.8", "Otras filariasis"),
    ("B74.9", "Filariasis, no especificada"),
    ("B75", "Triquinosis"),
    ("B76", "Anquilostomiasis y necatoriasis"),
    ("B76.0", "Anquilostomiasis"),
    ("B76.1", "Necatoriasis"),
    ("B76.8", "Otras enfermedades debidas a anquilostomas"),
    ("B76.9", "Enfermedad debida a anquilostomas, no especificada"),
    ("B77", "Ascariasis"),
    ("B77.0", "Ascariasis con complicaciones intestinales"),
    ("B77.8", "Ascariasis con otras complicaciones"),
    ("B77.9", "Ascariasis, no especificada"),
    ("B78", "Estrongiloidiasis"),
    ("B78.0", "Estrongiloidiasis intestinal"),
    ("B78.1", "Estrongiloidiasis cutánea"),
    ("B78.7", "Estrongiloidiasis diseminada"),
    ("B78.9", "Estrongiloidiasis, no especificada"),
    ("B79", "Tricuriasis"),
    ("B80", "Enterobiasis"),
    ("B81", "Otras helmintiasis intestinales, no clasificadas en otra parte"),
    ("B81.0", "Anisaquiasis"),
    ("B81.1", "Capilariasis intestinal"),
    ("B81.2", "Tricoestrongiliasis"),
    ("B81.3", "Angiostrongiliasis intestinal"),
    ("B81.4", "Helmintiasis intestinales mixtas"),
    ("B81.8", "Otras helmintiasis intestinales especificadas"),
    ("B82", "Parasitosis intestinal, sin otra especificación"),
    ("B82.0", "Helmintiasis intestinal, sin otra especificación"),
    ("B82.9", "Parasitosis intestinal, sin otra especificación"),
    ("B83", "Otras helmintiasis"),
    ("B83.0", "Larva migrans visceral"),
    ("B83.1", "Gnatostomiasis"),
    ("B83.2", "Angiostrongiliasis debida a Parastrongylus cantonensis"),
    ("B83.3", "Singamiasis"),
    ("B83.4", "Hirudiniasis interna"),
    ("B83.8", "Otras helmintiasis especificadas"),
    ("B83.9", "Helmintiasis, no especificada"),
    # B85-B89 Pediculosis, acariasis and other infestations
    ("B85", "Pediculosis y ftiriasis"),
    ("B85.0", "Pediculosis debida a Pediculus humanus capitis"),
    ("B85.1", "Pediculosis debida a Pediculus humanus corporis"),
    ("B85.2", "Pediculosis, no especificada"),
    ("B85.3", "Ftiriasis"),
    ("B85.4", "Pediculosis y ftiriasis mixtas"),
    ("B86", "Escabiosis"),
    ("B87", "Miasis"),
    ("B87.0", "Miasis cutánea"),
    ("B87.1", "Miasis de heridas"),
    ("B87.2", "Miasis ocular"),
    ("B87.3", "Miasis nasofaríngea"),
    ("B87.4", "Miasis auricular"),
    ("B87.8", "Miasis de otros sitios"),
    ("B87.9", "Miasis, no especificada"),
    ("B88", "Otras infestaciones"),
    ("B88.0", "Otras acariasis"),
    ("B88.1", "Tungiasis [infestación por pulga de arena]"),
    ("B88.2", "Otras infestaciones por artrópodos"),
    ("B88.3", "Hirudiniasis externa"),
    ("B88.8", "Otras infestaciones especificadas"),
    ("B88.9", "Infestación, no especificada"),
    ("B89", "Enfermedad parasitaria, no especificada"),
    # B90-B94 Sequelae of infectious and parasitic diseases
    ("B90", "Secuelas de tuberculosis"),
    ("B90.0", "Secuelas de tuberculosis del sistema nervioso central"),
    ("B90.1", "Secuelas de tuberculosis genitourinaria"),
    ("B90.2", "Secuelas de tuberculosis de huesos y articulaciones"),
    ("B90.8", "Secuelas de tuberculosis de otros órganos"),
    ("B90.9", "Secuelas de tuberculosis respiratoria y de tuberculosis no especificada"),
    ("B91", "Secuelas de poliomielitis"),
    ("B92", "Secuelas de lepra"),
    ("B94", "Secuelas de otras enfermedades infecciosas y parasitarias y las no especificadas"),
    ("B94.0", "Secuelas de tracoma"),
    ("B94.1", "Secuelas de encefalitis viral"),
    ("B94.2", "Secuelas de hepatitis viral"),
    ("B94.8", "Secuelas de otras enfermedades infecciosas y parasitarias especificadas"),
    ("B94.9", "Secuelas de enfermedades infecciosas y parasitarias no especificadas"),
    # B95-B98 Bacterial, viral and other infectious agents
    ("B95", "Estreptococos y estafilococos como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.0", "Estreptococo del grupo A como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.1", "Estreptococo del grupo B como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.2", "Estreptococo del grupo D como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.3", "Streptococcus pneumoniae como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.4", "Otros estreptococos como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.5", "Estreptococo no especificado como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.6", "Staphylococcus aureus como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.7", "Otros estafilococos como causa de enfermedades clasificadas en otros capítulos"),
    ("B95.8", "Estafilococo no especificado como causa de enfermedades clasificadas en otros capítulos"),
    ("B96", "Otros agentes bacterianos como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.0", "Mycoplasma pneumoniae como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.1", "Klebsiella pneumoniae como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.2", "Escherichia coli como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.3", "Haemophilus influenzae como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.4", "Proteus (mirabilis) (morganii) como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.5", "Pseudomonas como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.6", "Bacillus fragilis como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.7", "Clostridium perfringens como causa de enfermedades clasificadas en otros capítulos"),
    ("B96.8", "Otros agentes bacterianos especificados como causa de enfermedades clasificadas en otros capítulos"),
    ("B97", "Virus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.0", "Adenovirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.1", "Enterovirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.2", "Coronavirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.3", "Retrovirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.4", "Virus sincitial respiratorio como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.5", "Reovirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.6", "Parvovirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.7", "Papilomavirus como causa de enfermedades clasificadas en otros capítulos"),
    ("B97.8", "Otros virus como causa de enfermedades clasificadas en otros capítulos"),
    ("B99", "Otras enfermedades infecciosas y las no especificadas"),
]
